server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
  tomcat:
    connection-timeout: 30000

logging:
  config: classpath:logback/logback.xml

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh
